<?php

namespace AppBundle\Repository;

/**
 * RoomCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
